In [1]:

import pandas as pd
import numpy as np

In [2]:
diabetes = pd.read_csv('/home/julia/IDE/учеба Skillfactory/PY-14_Очистка данных/data/diabetes_data.csv')
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Gender
0,6,98,58,33,190,34.0,0.430,43,0,Female
1,2,112,75,32,0,35.7,0.148,21,0,Female
2,2,108,64,0,0,30.8,0.158,21,0,Female
3,8,107,80,0,0,24.6,0.856,34,0,Female
4,7,136,90,0,0,29.9,0.210,50,0,Female

Pregnancies — количество беременностей.

Glucose — концентрация глюкозы в плазме через два часа при пероральном тесте на толерантность к глюкозе.

BloodPressure — диастолическое артериальное давление (мм рт. ст.).

SkinThickness — толщина кожной складки трицепса (мм).

Insulin — двухчасовой сывороточный инсулин (ме Ед/мл).

BMI — индекс массы тела (вес в кг / (рост в м) в квадрате).

DiabetesPedigreeFunction — функция родословной диабета (чем она выше, тем выше шанс наследственной заболеваемости).

Age — возраст.

Outcome — наличие диабета (0 — нет, 1 — да).

In [3]:
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000
mean,3.848329,120.822622,69.035990,20.457584,79.521851,31.982262,0.470871,33.317481,0.344473
std,3.360782,31.883264,19.432323,15.954452,114.862405,7.853917,0.330669,11.816300,0.475502
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.241500,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,27.000000,32.000000,0.370000,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.000000,126.750000,36.500000,0.625500,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
dupl_diab_cols = list(diabetes.columns)
dupl_diab_mask = diabetes.duplicated()
dupl_diab = diabetes[dupl_diab_mask]
display(dupl_diab)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Gender
768,6,98,58,33,190,34.0,0.430,43,0,Female
769,2,112,75,32,0,35.7,0.148,21,0,Female
770,2,108,64,0,0,30.8,0.158,21,0,Female
771,8,107,80,0,0,24.6,0.856,34,0,Female
772,7,136,90,0,0,29.9,0.210,50,0,Female
773,6,103,72,32,190,37.7,0.324,55,0,Female
774,1,71,48,18,76,20.4,0.323,22,0,Female
775,0,117,0,0,0,33.8,0.932,44,0,Female
776,4,154,72,29,126,31.3,0.338,37,0,Female
777,5,147,78,0,0,33.7,0.218,65,0,Female

In [6]:
diabetes = diabetes.drop_duplicates()
print(diabetes.shape[0])

768

In [7]:
low_information_cols = []
for col in diabetes.columns:
    top_freq = diabetes[col].value_counts(normalize=True).max()
    nunique_ratio = diabetes[col].nunique() / diabetes[col].count()
    
    if top_freq > 0.95:
        low_information_cols.append(col)
        print(f'{col}: {round(top_freq*100, 2)} % одинаковых значений')
        
    if nunique_ratio > 0.95:
        low_information_cols.append(col)
        print(f'{col}: {round(nunique_ratio*100, 2)} % уникальных значений')

Gender: 100.0 % одинаковых значений

In [8]:
print(low_information_cols)

['Gender']

In [13]:
diabetes.drop(['Gender'], axis=1, inplace=True)
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98,58,33,190,34.0,0.430,43,0
1,2,112,75,32,0,35.7,0.148,21,0
2,2,108,64,0,0,30.8,0.158,21,0
3,8,107,80,0,0,24.6,0.856,34,0
4,7,136,90,0,0,29.9,0.210,50,0

In [17]:
def change_zero_to_nan(column_value):
    if column_value == 0:
        nan_value = np.nan
    else:
        nan_value = column_value
    return nan_value

columns_list = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI'] 
    
diabetes2 = diabetes.copy()

for col in columns_list:
    diabetes2[col] = diabetes2[col].apply(change_zero_to_nan)

display(diabetes2.head(20))

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98.0,58.0,33.0,190.0,34.0,0.430,43,0
1,2,112.0,75.0,32.0,NaN,35.7,0.148,21,0
2,2,108.0,64.0,NaN,NaN,30.8,0.158,21,0
3,8,107.0,80.0,NaN,NaN,24.6,0.856,34,0
4,7,136.0,90.0,NaN,NaN,29.9,0.210,50,0
5,6,103.0,72.0,32.0,190.0,37.7,0.324,55,0
6,1,71.0,48.0,18.0,76.0,20.4,0.323,22,0
7,0,117.0,NaN,NaN,NaN,33.8,0.932,44,0
8,4,154.0,72.0,29.0,126.0,31.3,0.338,37,0
9,5,147.0,78.0,NaN,NaN,33.7,0.218,65,0
10,10,111.0,70.0,27.0,NaN,27.5,0.141,40,1
11,7,179.0,95.0,31.0,NaN,34.2,0.164,60,0
12,4,148.0,60.0,27.0,318.0,30.9,0.150,29,1
13,5,96.0,74.0,18.0,67.0,33.6,0.997,43,0
14,2,88.0,58.0,26.0,16.0,28.4,0.766,22,0
15,1,125.0,50.0,40.0,167.0,33.3,0.962,28,1
16,3,84.0,72.0,32.0,NaN,37.2,0.267,28,0
17,5,86.0,68.0,28.0,71.0,30.2,0.364,24,0
18,4,183.0,NaN,NaN,NaN,28.4,0.212,36,1
19,0,140.0,65.0,26.0,130.0,42.6,0.431,24,1

In [31]:
not_nan_ins = diabetes2['Insulin'].isnull().value_counts()[0]
nan_ins = diabetes2['Insulin'].isnull().value_counts()[1] 
print(nan_insulin_proportion)
print(not_nan_ins, nan_ins)
nan_insulin_proportion = nan_ins / (not_nan_ins + nan_ins) * 100
print()
print(round(nan_insulin_proportion, 3))

48.69791666666667
394 374

48.698

In [33]:
col_null_persent = diabetes2.isnull().mean() * 100
print(col_null_persent)

Pregnancies                  0.000000
Glucose                      0.651042
BloodPressure                4.557292
SkinThickness               29.557292
Insulin                     48.697917
BMI                          1.432292
DiabetesPedigreeFunction     0.000000
Age                          0.000000
Outcome                      0.000000
dtype: float64

In [34]:
def nan_function(x):
    return np.nan if x == 0 else x
diabetes["Glucose"] = diabetes["Glucose"].apply(nan_function)
diabetes["BloodPressure"] = diabetes["BloodPressure"].apply(nan_function)
diabetes["SkinThickness"] = diabetes["SkinThickness"].apply(nan_function)
diabetes["Insulin"] = diabetes["Insulin"].apply(nan_function)
diabetes["BMI"] = diabetes["BMI"].apply(nan_function)
diabetes.isnull().mean().round(2).sort_values(ascending=False)

Insulin                     0.49
SkinThickness               0.30
BloodPressure               0.05
Glucose                     0.01
BMI                         0.01
Pregnancies                 0.00
DiabetesPedigreeFunction    0.00
Age                         0.00
Outcome                     0.00
dtype: float64

In [35]:
diabetes.drop(['Insulin'], axis=1, inplace=True)
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98.0,58.0,33.0,34.0,0.430,43,0
1,2,112.0,75.0,32.0,35.7,0.148,21,0
2,2,108.0,64.0,NaN,30.8,0.158,21,0
3,8,107.0,80.0,NaN,24.6,0.856,34,0
4,7,136.0,90.0,NaN,29.9,0.210,50,0

In [37]:
m = diabetes.shape[1] #число признаков после удаления столбцов
diabetes = diabetes.dropna(how='any', thresh=m-2, axis=0)
diabetes.shape[0]

761

In [38]:
values = {
    'Glucose': diabetes['Glucose'].median(),
    'BloodPressure': diabetes['BloodPressure'].median(),
    'SkinThickness': diabetes['SkinThickness'].median(),
    'BMI': diabetes['BMI'].median()
}

diabetes = diabetes.fillna(values)
print(diabetes['SkinThickness'].mean())

29.109067017082786

In [40]:
def outliers_iqr(data, feature):
    # классический метод межквартильного размаха
    x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    outliers = data[(x<lower_bound) | (x > upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned

outliers,cleaned = outliers_iqr(diabetes, 'SkinThickness')
print(outliers.shape[0])

87

In [45]:
def outliers_z_score(data, feature, log_scale=False):
    # классический метод z-отклонения - считается без логарифмов
    if log_scale:
        x = np.log(data[feature]+1)
    else:
        x = data[feature]
    mu = x.mean()
    sigma = x.std()
    lower_bound = mu - 3 * sigma
    upper_bound = mu + 3 * sigma
    outliers2 = data[(x < lower_bound) | (x > upper_bound)]
    cleaned2 = data[(x > lower_bound) & (x < upper_bound)]
    return outliers2, cleaned2
    


outliers2, cleaned2 = outliers_z_score(diabetes, 'SkinThickness', log_scale=False)

print(outliers2.shape[0])

4

In [46]:
def outliers_iqr(data, feature):
    # классический метод межквартильного размаха
    x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    outliers = data[(x<lower_bound) | (x > upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned

outliers,cleaned = outliers_iqr(diabetes, 'DiabetesPedigreeFunction')
outliers_pf_classic = outliers.shape[0]
print(outliers_pf_classic)

29

In [52]:
def outliers_iqr(data, feature, log_scale=False):
    # метод межквартильного размаха с логарифмированием
    if log_scale:
        x = np.log(data[feature])
    else:
        x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    outliers2 = data[(x<lower_bound) | (x > upper_bound)]
    cleaned2 = data[(x>lower_bound) & (x < upper_bound)]
    return outliers2, cleaned2

outliers2,cleaned2 = outliers_iqr(diabetes, 'DiabetesPedigreeFunction', log_scale=True)
outliers_pf_log = outliers2.shape[0]
print(outliers_pf_log)

0

In [53]:
print(outliers_pf_classic - outliers_pf_log)

29

In [58]:
class DepartmentReport():
    def add_revenue(self, amount):
          if not hasattr(self, 'revenues'):
              self.revenues = []
          self.revenues.append(amount)  
    
    def average_revenue(self):
        from statistics import mean
        return  sum(self.revenues) / len(self.revenues)
    
    revenues = [] 
    
    


report = DepartmentReport()
report.add_revenue(1_000_000)
report.add_revenue(400_000)
print(report.revenues)
# => [1000000, 400000]
print(report.average_revenue())
# => 700000.0

[1000000, 400000]
700000.0

In [60]:
class DepartmentReport():

    def __init__(self,company):
        """
        Метод инициализации класса. 
        Создаёт атрибуты revenues и company
        """
        self.revenues = []
        self.company = company
    
    def add_revenue(self, amount):
        """
        Метод для добавления выручки отдела в список revenues.
        Если атрибута revenues ещё не существует, метод должен создавать пустой список перед добавлением выручки.
        """
        self.revenues.append(amount)
    
    def average_revenue(self):
        """
        Вычисляет average_revenue — среднюю выручку по отделам — округляя до целого.
        Метод возвращает строку в формате:
        'Average department revenue for <company>: <average_revenue>'
        """
        average=round(sum(self.revenues) / len(self.revenues))
        return f'Average department revenue for {self.company}: {average}'
    
report = DepartmentReport("Danon")
report.add_revenue(1_000_000)
report.add_revenue(400_000)

print(report.average_revenue())
# => Average department revenue for Danon: 700000

Average department revenue for Danon: 700000

In [ ]:
 
class SalesReport():  
    def __init__(self, employee_name):  
        self.deals = []  
        self.employee_name = employee_name  
      
    def add_deal(self, company, amount):   
        self.deals.append({'company': company, 'amount': amount})  
          
    def total_amount(self):  
        return sum([deal['amount'] for deal in self.deals])  
      
    def average_deal(self):  
        return self.total_amount()/len(self.deals)  
      
    def all_companies(self):  
        return list(set([deal['company'] for deal in self.deals]))  
      
    def print_report(self):  
        print("Employee: ", self.employee_name)  
        print("Total sales:", self.total_amount())  
        print("Average sales:", self.average_deal())  
        print("Companies:", self.all_companies())  
      
      
report = SalesReport("Ivan Semenov")  
  
report.add_deal("PepsiCo", 120_000)  
report.add_deal("SkyEng", 250_000)  
report.add_deal("PepsiCo", 20_000)  
  
report.print_report()  
# => Employee:  Ivan Semenov  
# Total sales: 390000  
# Average sales: 130000.0  
# Companies: ['PepsiCo', 'SkyEng']

In [61]:
class User():
    def __init__(self, email, password, balance):
        self.email = email
        self.password = password
        self.balance = balance
        
    def login(self, email, password):
        if email == self.email and password == self.password:
            return True
        else:
            return False
    
    def update_balance(self, amount):
        self.balance += amount


user = User("gosha@roskino.org", "qwerty", 20_000)
user.login("gosha@roskino.org", "qwerty123")
# => False
user.login("gosha@roskino.org", "qwerty")
# => True
user.update_balance(200)
user.update_balance(-500)
print(user.balance)
# => 19700

19700

In [68]:
class IntDataFrame():  
    def __init__(self, list_nums):  
        # Инициализируем атрибуты
        self.list_nums = list_nums
        self.to_int()  
                 
    def to_int(self):  
        for i, value in enumerate(self.list_nums):  
            self.list_nums[i] = int(self.list_nums[i])  
                  
    def count(self):  
        count = 0
        for num in self.list_nums:
            if num != 0:
                count += 1
        return count
      
    def unique(self):  
        num_unique = len(list(set(self.list_nums)))
        return num_unique
      
 
df = IntDataFrame([4.7, 4, 3, 0, 2.4, 0.3, 4])

print(df.count())
# => 5
print(df.unique())
# => 4

5
4

In [72]:
class OwnLogger():
    def __init__ (self):
        self.info = []
        self.warning = []
        self.error = []
        self.all = []
    
    def log(self, message, level):
        if level == 'info':
            self.info.append(message)
            self.all.append(message)
        elif level == 'warning':
            self.warning.append(message)
            self.all.append(message)
        elif level == 'error':
            self.error.append(message)
            self.all.append(message)
        else:
            print('Wrong level! Please, choose one of following levels: info, warning, error')
    
    def show_last(self, level='all'):
           if level == 'all':
               try:
                   return self.all[-1]
               except IndexError:
                   return None
           if level == 'info':
               try:
                   return self.info[-1]
               except IndexError:
                   return None
           if level == 'warning':
               try:
                   return self.warning[-1]
               except IndexError:
                   return None
           if level == 'error':
               try:
                   return self.error[-1]
               except IndexError:
                   return None
           else:
               return None

logger = OwnLogger()
logger.log("System started", "info")
print(logger.show_last("error"))
# => None
# Некоторые интерпретаторы Python могут не выводить None, тогда в этой проверке у вас будет пустая строка
logger.log("Connection instable", "warning")
logger.log("Connection lost", "error")

print(logger.show_last())
# => Connection lost
print(logger.show_last("info"))
# => System started

None
Connection lost
System started

In [100]:
def get_files_list(adress):
    import os
    tree = list(os.walk(adress, topdown=False))
    #print(tree)
    files_list = tree[-1][1:][1:]
    return files_list

print(get_files_list('/home/julia/IDE/учеба Skillfactory/PY-14_Очистка данных/data'))

(['sber_data.csv', 'diabetes_data.csv'],)

In [101]:
import os

def walk_desc(path=None):
    start_path = path if path is not None else os.getcwd()

    for root, dirs, files in os.walk(start_path):
        print("Текущая директория", root)
        print("---")

        if dirs:
            print("Список папок", dirs)
        else:
            print("Папок нет")
        print("---")

        if files:
            print("Список файлов", files)
        else:
            print("Файлов нет")
        print("---")

        if files and dirs:
            print("Все пути:")
        for f in files:
            print("Файл ", os.path.join(root, f))
        for d in dirs:
            print("Папка ", os.path.join(root, d))
        print("===")
        
walk_desc('/home/julia/IDE/учеба Skillfactory/PY-14_Очистка данных/data')

Текущая директория /home/julia/IDE/учеба Skillfactory/PY-14_Очистка данных/data
---
Папок нет
---
Список файлов ['sber_data.csv', 'diabetes_data.csv']
---
Файл  /home/julia/IDE/учеба Skillfactory/PY-14_Очистка данных/data/sber_data.csv
Файл  /home/julia/IDE/учеба Skillfactory/PY-14_Очистка данных/data/diabetes_data.csv
===

In [102]:
line='Иванов О. 4'
score = float(str(line)[-1])
print(score)

4.0

In [106]:
try:
    i = int(input('Введите число:\t'))
except ValueError as e:
    print(e)
else:
    print(f'Вы ввели {i}')
finally:
    print('Выход из программы')

invalid literal for int() with base 10: 'xf'
Выход из программы